apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Krishnamukund450/rag-doc-qa-bot.git
    targetRevision: HEAD
    path: rag-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true