apiVersion: apps/v1
kind: Deployment

metadata:
  name: rag-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: rag-backend

  template:
    metadata:
      labels:
        app: rag-backend

    spec:

      serviceAccountName: rag-backend-sa

      containers:
        - name: rag-backend

          image: rag-doc-qa-bot-backend:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: OLLAMA_HOST

              valueFrom:
                configMapKeyRef:
                  name: rag-config
                  key: OLLAMA_HOST

            - name: MODEL_NAME

              valueFrom:
                configMapKeyRef:
                  name: rag-config
                  key: MODEL_NAME

            - name: SECRET_MESSAGE

              valueFrom:
                secretKeyRef:
                  name: rag-secret
                  key: SECRET_MESSAGE

          volumeMounts:
            - mountPath: /app/data
              name: rag-storage

            - mountPath: /app/db
              name: rag-storage

      volumes:
        - name: rag-storage

          persistentVolumeClaim:
            claimName: rag-backend-pvc